package com.dra.order_service.enums;

public enum OrderStatus {
    CANCELLATION_PROCESSING,
    CANCELLATION_SUCCESS,
    CREATION_FAILED,
    CREATION_PROCESSING,
    CREATION_SUCCESS,
    CANCELLATION_FAILED
}
